/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EGAMECIRCLE_AUTODEFS_H
#define S3EGAMECIRCLE_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_GAMECIRCLE_NAME "s3eGameCircle"
#define S3E_EXT_GAMECIRCLE_HASH 0x1b7f827c

#endif /* !S3EGAMECIRCLE_AUTODEFS_H */
